---
# tasks file for docker-fedora

- name: install packages
  dnf: 
    state: latest 
    name: "{{ item }}"
  with_items:
    - docker
    - lvm2

- name: create physical volume
  lvg:
    vg: "{{ vg }}"
    state: present
    pvs: "{{ pv }}"

- name: create docker thinpool logical volume
  lvol:
    lv: thinpool
    size: 95%VG
    state: present
    vg: "{{ vg }}"
    opts: "--wipesignatures y"

- name: create docker thinpool metadata logical volume
  lvol:
    lv: thinpoolmeta
    vg: "{{ vg }}"
    size: 1%VG
    opts: "--wipesignatures y"

- name: convert pool into thin pool
  command: lvconvert -y --zero n -c 512K --thinpool docker/thinpool --poolmetadata docker/thinpoolmeta
 
- name: create lvm profile directory
  file:
    state: directory
    path: /etc/lvm/profile
 
- name: set thinpool profile
  copy:
    src: docker-thinpool.profile
    dest: /etc/lvm/profile/docker-thinpool.profile

- name: apply lvm profile
  command: lvchange --metadataprofile docker-thinpool docker/thinpool

- name: add docker daemon config options
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: reload and start docker daemon
  systemd:
    daemon_reload: yes
    enabled: yes
    name: docker
    state: started

- name: install docker compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ os }}-{{ machine_architecture }}" 
    mode: 0755
    dest: /usr/local/bin/docker-compose

- name: create docker group
  group:
    name: docker
    state: present

- name: add user to docker group
  user:
    append: yes
    groups: docker
    state: present
    name: "{{ item }}"
  with_items: "{{ docker_users }}"
